# ../inputs/2024-02/part1-example.toml
# Simon Hulse
# simonhulse@protonmail.com
# Last Edited: Mon 09 Dec 2024 05:19:06 PM EST

input="""
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
"""
output = 2
