# ../inputs/2024-06/part1-example.toml
# Simon Hulse
# simonhulse@protonmail.com
# Last Edited: Wed 11 Dec 2024 03:54:42 PM EST

input="""
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"""

output = 41
